apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-gunicorn
  labels:
    app: django-gunicorn
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   # allow 1 pod to be unavailable during update
      maxSurge: 1         # allow 1 extra pod above desired replicas
  selector:
    matchLabels:
      app: django-gunicorn
  template:
    metadata:
      labels:
        app: django-gunicorn
    spec:
      containers:
      - name: django-gunicorn
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/rak-django-gunicorn:latest
        ports:
        - containerPort: 8000
        envFrom: 
        - secretRef:
            name: rds-redis-credentials
        volumeMounts:
        - name: static-files
          mountPath: /opt/status-page/statuspage/static
      imagePullSecrets:
        - name: image-pull
      volumes:
      - name: static-files
        persistentVolumeClaim:
          claimName: static-files-pvc
