apiVersion: v1
kind: Service
metadata:
  name: django-gunicorn-svc
spec:
  selector:
    app: django-gunicorn
  ports:
    - port: 80     # service port
      targetPort: 8000  # container port
  type: LoadBalancer
~
~
~
~
